name: Publish FluentPipelines to NuGet

on:
  push:
    tags:
      - main-v[0-9]+.[0-9]+.[0-9]+
      - main-v[0-9]+.[0-9]+.[0-9]+-*

env:
  PROJECT_FILE: ./FluentPipelines/FluentPipelines.csproj

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build $PROJECT_FILE -c Release --no-restore

      - name: Test
        run: dotnet test $PROJECT_FILE --no-build --verbosity normal

  Publish:
    needs: [BuildAndTest]
    runs-on: ubuntu-latest
    if: (github.ref_type == 'tag')
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Package project
        run: dotnet pack $PROJECT_FILE -c Release "/p:PackageOutputPath=$GITHUB_WORKSPACE/artifacts" "/p:Version=${GITHUB_REF_NAME##main-v}" /p:RepositoryCommit=$GITHUB_SHA "/p:Authors=Visual Vincent"

      - name: Publish NuGet package
        run: dotnet nuget push "$GITHUB_WORKSPACE/artifacts/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
